permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
markdown: kramdown

title : 尘世客
tagline: 尘世客博客
author : 
  name : fatalistim
  email : blah@email.test
  github : fatalistim
  twitter : username
  feedburner : feedname
  
production_url : http://fatalistim.github.io

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  
